### ISSUE TITLE
Getting dependencies

### ISSUE THREAD

**Issue by giovannitubera** [Furqankhanzada/flutter_eCommerce_ui_kit#2]
Hi. Apologies for this request do i need to down grade my SDK version to your version before installing/ getting your packages dependencies? 

![problem](https://user-images.githubusercontent.com/51511592/68220003-e38fe300-0021-11ea-825f-c332ed121901.png)

**Comment by Furqankhanzada** [comment]
@giovannitubera downgrade you `cached_network_image: 2.0.0-rc` version to `cached_network_image: ^1.1.3` and it will work.

I am working on flutter web and `cached_network_image: ^1.1.3` does not work with it thats why i updated it to `cached_network_image: 2.0.0-rc`

**Comment by syahjamal** [comment]
where chace_network_image place, same issue with @giovannitubera

**Comment by syahjamal** [comment]
Running "flutter pub get" in flutter_eCommerce_ui_kit...        Because every version of flutter_localizations from sdk depends on intl 0.15.8 and flutter_scaffold depends on intl ^0.16.0, flutter_localizations from sdk is forbidden.

So, because flutter_scaffold depends on flutter_localizations any from sdk, version solving failed.

pub get failed (1)


i was change chace_network_image and get packages again ang get this

**Comment by blittable** [comment]
@giovannitubera @Furqankhanzada I hit this issue - but it was fine after I changed to the dev channel.
